"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class vicon_ballstate(object):
    __slots__ = ["timestamp", "x", "y", "z"]

    def __init__(self):
        self.timestamp = 0
        self.x = 0.0
        self.y = 0.0
        self.z = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(vicon_ballstate._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddd", self.timestamp, self.x, self.y, self.z))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != vicon_ballstate._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vicon_ballstate._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vicon_ballstate()
        self.timestamp, self.x, self.y, self.z = struct.unpack(">qddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vicon_ballstate in parents: return 0
        tmphash = (0x56ddf40ba7d64ce2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vicon_ballstate._packed_fingerprint is None:
            vicon_ballstate._packed_fingerprint = struct.pack(">Q", vicon_ballstate._get_hash_recursive([]))
        return vicon_ballstate._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

